### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by srivathsapv** [NeuroDataDesign/bloby#12]
<img width="675" alt="screen shot 2018-02-19 at 1 23 43 pm" src="https://user-images.githubusercontent.com/1017519/36443566-24e2fc96-1647-11e8-8e13-4b99bbcb5d4a.png">

**Comment by srivathsapv** [comment]
<img width="691" alt="screen shot 2018-02-20 at 2 11 55 pm" src="https://user-images.githubusercontent.com/1017519/36443912-1c1ea10e-1648-11e8-81f4-e5348b94ede0.png">

**Comment by srivathsapv** [comment]
<img width="661" alt="screen shot 2018-02-20 at 2 44 40 pm" src="https://user-images.githubusercontent.com/1017519/36445537-9b46d7b8-164c-11e8-918b-fa1af892dea6.png">
<img width="657" alt="screen shot 2018-02-20 at 2 37 19 pm" src="https://user-images.githubusercontent.com/1017519/36445540-9f364b24-164c-11e8-8f18-0c79dd8b8fcd.png">

**Comment by vikramc1** [comment]
closing this since it isn't a bug in the code anymore
